import mesa
import model.agent_defaults
import numpy as np

from typing import Self, TYPE_CHECKING

if TYPE_CHECKING:
    from model.model import ReductionModel


class ReductionAgent(mesa.Agent):
    """A speaker in the model"""

    def __init__(self, reduction_model: "ReductionModel"):
        """Initialise a ReductionModel agent

        Args:
            reduction_model (ReductionModel):
            The ReductionModel for which the agent is initialised
        """

        # Pass the parameters to the parent class.
        super().__init__(reduction_model)
        self.model: "ReductionModel" = reduction_model

        # Populate the agent's parameters based off the model parameters
        self.atts = model.agent_defaults.Attributes(
            vocabulary=self.model.params.vocabulary
        )

    def interact_do(self):
        # Choose a random other agent that is not the agent itself
        hearer_agent = self.model.get_random_agent(self)

        # If there *is* an interaction, do interact
        self.interact(hearer_agent)

    def interact(self, hearer_agent: Self):
        # Choose a random construction based on the selected probabilities
        # Also, save this in the tracker
        chosen_construction_index = self.model.get_random_construction_index()
        self.model.tracker.register_construction_chosen(chosen_construction_index)

        # Now, generate a vector for that specific construction
        vector = self.atts.vocabulary.get_construction_vector(chosen_construction_index)
        # Check whether we are going to reduce
        do_reduction = (
            self.model.params.nprandom.random() < self.model.params.reduction_prob
        )
        # If so, reduce with the specified reduction method, else pass
        if do_reduction:
            reduced_vector = self.model.params.reduction.get_reduced_vector(vector)
        else:
            reduced_vector = vector

        # Now, the other agent "hears" the construction that we just chose
        hearer_agent.receive_construction(reduced_vector, chosen_construction_index)

    # update vocabulary distributions etc.
    def receive_construction(
        self, heard_vector: np.ndarray, true_construction_index: int
    ):
        # First, we calculate the log probabilities
        # For each ctx, we check the probability that this vector was generated by that ctx
        log_scores = [
            ctx.calculate_log_score(heard_vector) for ctx in self.atts.vocabulary.words
        ]

        # Re-check what is going on here
        win_index = np.argmax(log_scores)
        max_score = np.max(log_scores)  # winning score
        exp_scores = np.exp(log_scores - max_score)
        weights = exp_scores / np.sum(exp_scores)

        # Update category representations!
        for ctx, weight in zip(self.atts.vocabulary.words, weights):
            ctx.update(heard_vector, weight)

        # TODO: add uncertainty step

        communication_successful = true_construction_index == win_index
        self.model.tracker.register_communication_result(int(communication_successful))
        self.model.tracker.register_win_index(int(win_index), true_construction_index)
