import mesa
import model.agent_defaults
import numpy as np
import model.enums
import model.entropy

from typing import Self, TYPE_CHECKING, Tuple

if TYPE_CHECKING:
    from model.model import ReductionModel


class ReductionAgent(mesa.Agent):
    """A speaker in the model"""

    def __init__(self, reduction_model: "ReductionModel"):
        """Initialise a ReductionModel agent

        Args:
            reduction_model (ReductionModel):
            The ReductionModel for which the agent is initialised
        """

        # Pass the parameters to the parent class.
        super().__init__(reduction_model)
        self.model: "ReductionModel" = reduction_model

        # Populate the agent's parameters based off the model parameters
        self.atts = model.agent_defaults.Attributes(
            vocabulary=self.model.params.vocabulary
        )

    def interact_do(self):
        # Choose a random other agent that is not the agent itself
        hearer_agent = self.model.get_random_agent(self)

        # If there *is* an interaction, do interact
        self.interact(hearer_agent)

    def interact(self, hearer_agent: Self):
        # Choose a random construction based on the selected probabilities
        # Also, save this in the tracker
        chosen_construction_index = self.model.get_random_construction_index()
        self.model.tracker.register_construction_chosen(chosen_construction_index)

        # Now, generate a vector for that specific construction
        vector = self.atts.vocabulary.get_construction_vector(chosen_construction_index)
        # Check whether we are going to reduce
        do_reduction = (
            self.model.params.nprandom.random() < self.model.params.reduction_prob
        )
        # If so, reduce with the specified reduction method, else pass
        if do_reduction:
            reduced_vector = self.model.params.reduction.get_reduced_vector(vector)
        else:
            reduced_vector = vector

        reentrance_used = False
        if self.model.params.reentrance:
            win_index, log_scores = self.get_construction_winner(reduced_vector)

            # If the win index does not match the chosen construction index,
            # we do not understand ourselves and we reverse the reduction
            if win_index != chosen_construction_index:
                reduced_vector = vector
                do_reduction = False
                reentrance_used = True
        self.model.tracker.register_reentrance_usage(int(reentrance_used))

        # Now, the other agent "hears" the construction that we just chose
        hearer_agent.receive_construction(
            reduced_vector, chosen_construction_index, do_reduction
        )

    def get_construction_winner(
        self, heard_vector: np.ndarray
    ) -> Tuple[int, np.ndarray]:
        # First, we calculate the log probabilities
        # For each ctx, we check the probability that this vector was generated by that ctx
        log_scores = self.atts.vocabulary.calculate_log_score(heard_vector)

        # Which construction has the highest score?
        win_index = np.argmax(log_scores)

        return int(win_index), log_scores

    # update vocabulary distributions etc.
    def receive_construction(
        self, heard_vector: np.ndarray, true_construction_index: int, is_reduced: bool
    ):
        win_index, log_scores = self.get_construction_winner(heard_vector)

        # What is the highest score?
        max_score = np.max(log_scores)
        # Compute difference with max score
        exp_scores = np.exp(log_scores - max_score)
        # Turn into weights
        weights = exp_scores / np.sum(exp_scores)

        # The entropy of the current decision
        # How certain are we making this decision?
        score_probabilities = np.exp(log_scores)
        decision_entropy = model.entropy.compute_entropy(
            score_probabilities / np.sum(score_probabilities)
        )
        self.model.tracker.register_decision_entropy(decision_entropy)

        if self.model.params.to_update == model.enums.ToUpdate.DISTRIBUTED:
            # Update category representations!
            for ctx_index, weight in zip(
                self.model.params.construction_indices, weights
            ):
                self.atts.vocabulary.update_distribution(
                    ctx_index,
                    heard_vector,
                    weight,
                    learning_rate=self.model.params.learning_rate,
                )
        elif self.model.params.to_update == model.enums.ToUpdate.WINNER_ONLY:
            # Update only the winner with full weights
            self.atts.vocabulary.update_distribution(
                int(win_index),
                heard_vector,
                learning_rate=self.model.params.learning_rate,
            )
        else:
            raise ValueError("Unknown update destination")

        # TODO: add uncertainty step if needed

        communication_successful = true_construction_index == win_index
        self.model.tracker.register_communication_result(int(communication_successful))
        self.model.tracker.register_win_index(int(win_index), true_construction_index)

        if is_reduced:
            self.model.tracker.register_reduction_outcome(int(communication_successful))
