class ReductionModes:
    ALWAYS = 0
    L1_SUCCESS_DEPENDENT = 1
    SUCCESS_DEPENDENT_MICRO = 2
    SUCCESS_DEPENDENT_MACRO = 3

class ReductionMethod:
    DIMENSION_SCRAP = 0
    SOFT_THRESHOLDING = 1
    SOFT_THRESHOLDING_DIM = 4
    GAUSSIAN_MASK = 2
    ANGLE = 3
    TAPER = 5
    NON_LINEAR = 6
    BYE_MAX = 7